
%%
configFile                          = 'setup/SimulationSetup_EX4.yaml';
SimulationSetting                   = ReadYaml(configFile); 
SimulationSetting.default_baud_rate = 50;

[LightPathSet, isEdgeUseSlot, info] = main(SimulationSetting);

%%
fprintf("Running time = %g seconds\n",info('Time'));

%%
pause(0.1);
figure(87),
clf;
imagesc(logical(isEdgeUseSlot), 'CDataMapping', 'scaled');colorbar
title('Spectrum Usage Graph');
xlabel('Slot');
ylabel('Edge');
hold off;
%%
itemName = {...
    'sourceNo'...
    , 'destinationNo'...
    , 'capacity'...
    , 'cost'...
    , 'strPath'...
    , 'wavelengthNo'...
    , 'transceiverNo'...
    , 'transmissionModeNo'...
    }; 
printLightPathSet(...
    LightPathSet, ...
    itemName, ...
    'test.txt', 'w+');
% type test.txt