function val = getNumeric(obj,keyName)
    % get properties of <keyName> in array class <obj>
    narginchk(2,2);
    
    
    
    assert(any(strcmp(fieldnames(obj(1)), keyName))...
        , 'MATLAB:getValue:InvalidProperty' ...
        , 'No such properties');
    assert(isnumeric(obj(1).(keyName)) ...
        , 'MATLAB:getValue:TypeError'... 
        , 'This function only supports indexing numeric value');
    val = arrayfun(@(this) this.(keyName) ...
        , obj ...
        ,'UniformOutput',true...
        );
end
